spring:
  application:
    name: spring-ai-console-chat
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
settings:
  input:
    source: "input-sources/htmlcheatsheet.pdf"